import {Game,THEMES,matchWords,voiceMatch} from './core.js';
import {Voice} from './voice.js';
import {Motion} from './motion.js';
const $=id=>document.getElementById(id),key='dictai-game-round-v1';
const safeGet=k=>{try{return localStorage.getItem(k);}catch{return null;}};
const safeSet=(k,v)=>{try{localStorage.setItem(k,v);}catch{}};
const removeSave=()=>{try{localStorage.removeItem(key);}catch{}};
const themeNames={sky:'☀ Sky',neon:'ϟ Neon',paper:'✂ Paper',space:'✦ Space',sunset:'◒ Sunset'};
let game=null,lastTime=0,lastSave=0,displayed=null,composing=false,compositionTarget=null,deferredSelect=null,countEpoch=0,audioEpoch=0,busy=false,speed=1,catalog=null,modeBeforeOptions='ready',resultTimer=0;
let settings;try{settings=JSON.parse(safeGet('dictai-game-voice-settings')||'null');}catch{}settings={model:'full',beam:12,threshold:.72,candidate:.08,...settings};
let audio=new Audio(),cache=new Map();audio.preload='auto';
const motion=new Motion();let bestScore=Number(safeGet('dictai-game-best'))||0;
$('record').textContent=`BEST ${bestScore}`;
for(const id of ['effectLevel','pauseEffects'])$(id).onchange=()=>motion.applyLevel($(id).value);
for(const id of ['soundToggle','pauseSound'])$(id).onclick=()=>{motion.sound=!motion.sound;for(const name of ['soundToggle','pauseSound']){$(name).textContent=motion.sound?'Sound On':'Sound Off';$(name).setAttribute('aria-pressed',String(motion.sound));}if(!motion.sound)motion.silence();};
const voice=new Voice((words,id,epoch)=>{if(game?.status!=='running'||id!==game.active||epoch!==voice.epoch)return;for(const word of words){if(game.active!==id)break;const q=game.current;if(!q)break;const match=voiceMatch(q,word,settings);if(match.kind==='correct'){if(match.partial)q.partial=match.partial;const origins=motion.origins(match.indices);const solved=game.mark(match.indices);renderWords(q);motion.charge(origins,q,match.indices);if(solved)finish(solved);}}save();},label=>{$('voiceStatus').textContent=label;$('voiceButton').textContent=voice.enabled?'◉ Voice On':'◉ Voice Off';$('voiceButton').setAttribute('aria-pressed',String(voice.enabled));});
function feedback(s,kind=''){$('feedback').textContent=s;$('feedback').dataset.kind=kind;}
function save(){if(!game)return;saveDraft();safeSet(key,JSON.stringify(game));}
function saveDraft(){const q=game?.questions.find(q=>q.uid===displayed);if(q){q.draft=$('answer').value;q.caret=$('answer').selectionStart||0;}}
function applyTheme(theme){if(!THEMES.includes(theme))theme='sky';document.body.dataset.theme=theme;safeSet('dictai-game-theme',theme);document.querySelectorAll('[data-theme-choice]').forEach(b=>{b.classList.toggle('chosen',b.dataset.themeChoice===theme);b.setAttribute('aria-pressed',String(b.dataset.themeChoice===theme));});}
for(const holder of ['readyThemes','themes'])for(const theme of THEMES){const b=document.createElement('button');b.textContent=themeNames[theme];b.dataset.themeChoice=theme;b.onclick=()=>applyTheme(theme);$(holder).append(b);}applyTheme(safeGet('dictai-game-theme'));
function setControls(){const enabled=game?.status==='running'&&!!game.current;for(const id of ['answer','submit','skip','replay'])$(id).disabled=!enabled;$('pause').disabled=!game||!['running','paused'].includes(game.status);}
function point(q){const a=$('arena');const radius=innerHeight<720?38:45;return {x:Math.max(radius+8,Math.min(a.clientWidth-radius-8,q.x*a.clientWidth)),y:-radius+q.y*(a.clientHeight-16)};}
function draw(){motion.update(game);if(!game)return;$('score').textContent=game.score;$('hearts').textContent='♥ '.repeat(game.life)+'♡ '.repeat(5-game.life);$('hearts').setAttribute('aria-label',`${game.life} lives`);$('combo').textContent=game.combo?`COMBO ×${game.combo}`:`${game.questions.filter(q=>q.state==='solved').length} / ${game.questions.length}`;
  for(const q of game.questions){let b=$('bubble-'+q.uid);if(q.state!=='falling'){if(b&&!b.classList.contains('resolving'))b.remove();continue;}if(!b){b=document.createElement('button');b.className='bubble';b.id='bubble-'+q.uid;motion.decorate(b,q);const label=document.createElement('small');b.append(label);b.onclick=()=>select(q.uid);$('targets').append(b);}const p=point(q);b.style.left=p.x+'px';b.style.top=p.y+'px';b.classList.toggle('active',q.uid===game.active);b.classList.toggle('danger',q.y>.78);b.querySelector('small').textContent=`${q.uid===game.active?'▶ ':''}Q${String(q.number).padStart(2,'0')} · ${q.solved.length}/${q.words.length}`;b.setAttribute('aria-label',`Question ${q.number}, ${q.solved.length} of ${q.words.length} words, ${q.uid===game.active?'selected':'select'}`);b.setAttribute('aria-pressed',String(q.uid===game.active));}
  const q=game.current;const aim=$('aim');aim.hidden=!q;if(q){const p=point(q),dx=p.x-$('arena').clientWidth/2,dy=$('arena').clientHeight-20-p.y;aim.style.height=Math.hypot(dx,dy)+'px';aim.style.transform=`rotate(${Math.atan2(dx,dy)}rad)`;}$('charge').style.width=q?`${q.solved.length/q.words.length*100}%`:'0%';setControls();}
function renderWords(q=game?.current){if(!q)return;$('words').replaceChildren();let count=0,turn=0;for(let i=0;i<q.words.length;i++){if(q.turn_lengths?.length&&i===count+q.turn_lengths[turn]){count+=q.turn_lengths[turn++];const br=document.createElement('span');br.className='turn-break';$('words').append(br);}const b=document.createElement('button');b.id='word-'+i;b.className='word'+(q.solved.includes(i)?' done':'')+(q.hints.includes(i)?' hint':'')+(turn%2?' turn-b':'');b.textContent=q.solved.includes(i)?q.words[i]:'━';b.setAttribute('aria-label',q.solved.includes(i)?q.words[i]:`Reveal word ${i+1}`);b.onclick=()=>{if(game?.current!==q||game.status!=='running')return;const origins=motion.origins([i]);const wasSolved=q.solved.includes(i);const solved=game.mark([i],true);renderWords(q);if(!wasSolved)motion.charge(origins,q,[i],true);feedback('Hint used · This bubble earns no points.');if(solved)finish(solved);save();};$('words').append(b);}}
function syncTarget(autoPlay=true){const q=game?.current;if(q?.uid===displayed)return;if(composing){deferredSelect=q?.uid||null;return;}saveDraft();displayed=q?.uid||null;voice.setContext(displayed);stopAudio();$('answer').value=q?.draft||'';if(q){$('questionLabel').textContent=`Q${String(q.number).padStart(2,'0')} · ${q.label}`;renderWords();feedback('Space or Enter to submit');setControls();$('answer').setSelectionRange(q.caret||0,q.caret||0);if(autoPlay)void play();}else{$('words').replaceChildren();$('questionLabel').textContent='Next bubble incoming…';}draw();}
function select(id){if(game?.status!=='running')return;if(composing){deferredSelect=id;return;}saveDraft();game.select(id);syncTarget();save();$('answer').focus({preventScroll:true});}
function stopAudio(){audioEpoch++;audio.pause();voice.suspend();motion.silence();}
async function play(){const q=game?.current;if(!q||game.status!=='running')return;stopAudio();const epoch=audioEpoch;const url=cache.get(q.id);if(!url){feedback('Audio unavailable. Game paused.','wrong');pause('Audio unavailable');return;}audio.src=url;audio.playbackRate=speed;audio.currentTime=0;$('replay').textContent='↻';try{await audio.play();if(epoch!==audioEpoch)audio.pause();}catch{if(epoch===audioEpoch){pause('Tap Resume to enable audio');}}}
audio.addEventListener('ended',()=>{const epoch=audioEpoch;setTimeout(()=>{if(epoch===audioEpoch&&game?.status==='running')voice.resume();},350);});
audio.addEventListener('error',()=>{if(game?.status==='running')pause('Audio could not play. Resume to retry.');});
function burst(q,label){motion.floatText(point(q),label);}
function finish(q){saveDraft();motion.launch(q,point(q));
  if(game.score>bestScore){bestScore=game.score;safeSet('dictai-game-best',String(bestScore));$('record').textContent=`BEST ${bestScore}`;}
  if(composing){deferredSelect=game.active;return;}syncTarget();draw();maybeEnd();save();}

function submit(){if(composing||game?.status!=='running'||!game.current)return;const q=game.current;const result=matchWords(q,$('answer').value);if(result.kind==='empty')return;if(result.kind!=='correct'){feedback(result.kind==='duplicate'?'Already entered — your text is kept.':'Not a match. Try again.',result.kind);if(result.kind==='duplicate')for(const el of $('words').children)if(el.textContent&&el.textContent.toLowerCase().replace(/\.$/,'')===$('answer').value.trim().toLowerCase().replace(/\.$/,''))motion.animate(el,[{background:'#ffe289'},{background:'#b3f2ce'}],{duration:500});return;}const origins=motion.origins(result.indices);$('answer').value='';q.draft='';q.caret=0;q.partial=result.partial||{};const done=game.mark(result.indices);feedback(result.indices.length?'Nice! Keep going.':'Part of a contraction found. Keep going.');renderWords(q);motion.charge(origins,q,result.indices);motion.tone(q.solved.length/q.words.length,!voice.enabled&&audio.paused);draw();if(done)finish(done);save();}
$('answerForm').onsubmit=e=>{e.preventDefault();submit();};$('answer').addEventListener('keydown',e=>{if(e.code==='Space'&&!e.isComposing&&!composing){e.preventDefault();submit();}});$('answer').addEventListener('input',()=>{saveDraft();save();});$('answer').addEventListener('compositionstart',()=>{composing=true;compositionTarget=displayed;});$('answer').addEventListener('compositionend',()=>{saveDraft();composing=false;compositionTarget=null;if(deferredSelect){game?.select(deferredSelect);deferredSelect=null;}syncTarget();maybeEnd();});
$('skip').onclick=()=>{if(composing)return;saveDraft();const q=game?.skip();if(q){burst(q,'−♥');syncTarget();draw();maybeEnd();save();}};$('replay').onclick=()=>void play();document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.rate);document.querySelectorAll('[data-rate]').forEach(x=>x.classList.toggle('selected',x===b));if(game?.status==='running')void play();});
function hideSheets(){for(const id of ['ready','pauseSheet','options','result'])$(id).hidden=true;}
function pause(reason='Paused'){if(!game||!['running','paused'].includes(game.status))return;countEpoch++;$('countdown').hidden=true;saveDraft();game.status='paused';stopAudio();void voice.stop();hideSheets();$('pauseTitle').textContent=reason;$('pauseSheet').hidden=false;save();draw();}
async function resume(){if(!game||busy)return;hideSheets();await countdown();}
async function countdown(){const epoch=++countEpoch;game.status='paused';setControls();$('countdown').hidden=false;for(const n of ['3','2','1']){if(epoch!==countEpoch||document.hidden)return;$('countdown').textContent=n;await new Promise(r=>setTimeout(r,600));}if(epoch!==countEpoch||document.hidden)return;$('countdown').hidden=true;game.status='running';lastTime=performance.now();game.tick(0);syncTarget(false);draw();$('answer').focus({preventScroll:true});void play();save();}
$('pause').onclick=()=>pause();$('themeButton').onclick=()=>{if(game&&['running','paused'].includes(game.status))pause('Choose your theme');else if(!$('ready').hidden)$('readyThemes').scrollIntoView({block:'nearest'});};$('resume').onclick=resume;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&['running','paused'].includes(game.status))pause();});window.addEventListener('pagehide',()=>{save();stopAudio();void voice.stop();});
function maybeEnd(){if(!game||!['clear','over'].includes(game.status)||composing)return;clearTimeout(resultTimer);stopAudio();void voice.stop();save();setControls();resultTimer=setTimeout(()=>{if(!game||!['clear','over'].includes(game.status))return;hideSheets();$('result').hidden=false;$('resultTitle').textContent=game.status==='clear'?'Round cleared!':'One more try?';$('resultScore').textContent=game.score;$('resultDetail').textContent=`${game.questions.filter(q=>q.state==='solved').length} bubbles popped · Best combo ×${game.best}`;},700);}
function resetToReady(){motion.clear();motion.setPaused(true);countEpoch++;clearTimeout(resultTimer);stopAudio();void voice.stop();game=null;displayed=null;removeSave();hideSheets();$('ready').hidden=false;$('targets').replaceChildren();$('effects').replaceChildren();$('words').replaceChildren();$('answer').value='';$('restore').hidden=true;$('pause').disabled=true;setControls();}
$('newRound').onclick=resetToReady;$('choose').onclick=resetToReady;$('retry').onclick=()=>{motion.clear();const rows=game.questions.map(q=>({...q}));game=new Game(rows,game.difficulty);displayed=null;$('targets').replaceChildren();$('words').replaceChildren();$('answer').value='';hideSheets();void countdown();};
async function preload(rows){cache.forEach(url=>URL.revokeObjectURL(url));cache.clear();let cursor=0,done=0;await Promise.all(Array.from({length:Math.min(3,rows.length)},async()=>{while(cursor<rows.length){const row=rows[cursor++];const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(row.audio,{signal:controller.signal});if(!response.ok)throw Error('Audio not ready');const blob=await response.blob();if(blob.size<44)throw Error('Empty audio');cache.set(row.id,URL.createObjectURL(blob));done++;$('loadStatus').textContent=`Preparing audio ${done} / ${rows.length}`;}finally{clearTimeout(timer);}}}));}
async function start(){if(busy)return;busy=true;$('start').disabled=true;$('start').textContent='Preparing round…';try{const request={mode:$('source').value,level:$('level').value,topic:$('topic').value,chapter:Number($('chapter').value),count:20};safeSet('dictai-game-selection',JSON.stringify(request));const r=await fetch('/game-api/round',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(25000)});const payload=await r.json();if(!r.ok)throw Error(payload.detail||'Could not load questions');await preload(payload.questions);motion.clear();game=new Game(payload.questions,$('difficulty').value);displayed=null;$('targets').replaceChildren();$('answer').value='';$('loadStatus').textContent='';hideSheets();await countdown();}catch(e){$('loadStatus').textContent=e.name==='TimeoutError'?'Connection timed out. Try again.':e.message;}finally{busy=false;$('start').disabled=false;$('start').textContent='Let’s play →';}}
$('start').onclick=start;
$('restore').onclick=async()=>{if(busy)return;busy=true;$('restore').disabled=true;try{game=Game.restore(JSON.parse(safeGet(key)));await preload(game.questions);hideSheets();displayed=null;game.auto();syncTarget(false);pause('Welcome back');}catch(e){game=null;$('loadStatus').textContent='Saved round unavailable. Start a new round.';}finally{busy=false;$('restore').disabled=false;}};
function sourceChanged(){$('conversationSetup').hidden=$('source').value==='book';$('bookSetup').hidden=$('source').value!=='book';}function topics(){const current=$('topic').value;$('topic').replaceChildren();for(const name of ['Random',...catalog.levels[$('level').value]]){const o=new Option(name,name);$('topic').add(o);}if([...$('topic').options].some(o=>o.value===current))$('topic').value=current;}$('source').onchange=sourceChanged;$('level').onchange=topics;
$('voiceButton').onclick=async()=>{motion.silence();await voice.enable(!voice.enabled);$('voiceButton').textContent=voice.enabled?'◉ Voice On':'◉ Voice Off';$('voiceButton').setAttribute('aria-pressed',String(voice.enabled));if(voice.enabled&&audio.paused&&game?.status==='running')voice.resume();};
$('optionsButton').onclick=()=>{modeBeforeOptions=game?.status||'ready';if(game?.status==='running')pause();hideSheets();$('options').hidden=false;for(const name of ['model','beam','threshold','candidate'])$(name).value=settings[name];updateValues();};function updateValues(){for(const k of ['beam','threshold','candidate'])$(k+'Value').textContent=k==='beam'?$(k).value:Number($(k).value).toFixed(2);}for(const k of ['beam','threshold','candidate'])$(k).oninput=updateValues;
function closeOptions(){$('options').hidden=true;if(game&&['paused','running'].includes(game.status))pause();else if(game&&['clear','over'].includes(game.status))maybeEnd();else $('ready').hidden=false;}$('closeOptions').onclick=closeOptions;
$('apply').onclick=()=>{const next={model:$('model').value,beam:Number($('beam').value),threshold:Number($('threshold').value),candidate:Number($('candidate').value)};const reload=(window.wasmAsrRecognizer||voice.loading)&&(next.model!==settings.model||next.beam!==settings.beam);settings=next;safeSet('dictai-game-voice-settings',JSON.stringify(next));safeSet('dictai-game-voice-model',next.model);save();if(reload){sessionStorage.setItem('dictai-game-voice-restore',String(voice.enabled));location.reload();}else closeOptions();};
async function init(){try{const r=await fetch('/game-api/catalog',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Could not load catalog');catalog=await r.json();for(const level of Object.keys(catalog.levels))$('level').add(new Option(level,level));for(const b of catalog.books)$('chapter').add(new Option(`${b.chapter} · ${b.title}`,b.chapter));$('chapter').value='5';topics();try{const s=JSON.parse(safeGet('dictai-game-selection'));if(s){$('source').value=s.mode;$('level').value=s.level;topics();$('topic').value=s.topic;$('chapter').value=s.chapter;}}catch{}sourceChanged();$('start').disabled=false;$('start').textContent='Let’s play →';try{const saved=JSON.parse(safeGet(key));$('restore').hidden=!saved||!['running','paused','ready'].includes(saved.status);}catch{}if(sessionStorage.getItem('dictai-game-voice-restore')==='true'){sessionStorage.removeItem('dictai-game-voice-restore');await voice.enable(true);}}catch(e){$('loadStatus').textContent=e.message;$('start').textContent='Reload';$('start').disabled=false;$('start').onclick=()=>location.reload();}}
function frame(now){const dt=lastTime?Math.min(.25,(now-lastTime)/1000):0;lastTime=now;if(game?.status==='running'){const events=game.tick(dt);for(const e of events){if(e.type==='miss'){motion.floatText(point(e.q),'−♥');motion.animate($('hearts'),[{scale:'1'},{scale:'1.14',color:'#fff'},{scale:'1',color:'#ff7d8c'}],{duration:400});}else if(e.type==='wave')motion.banner(`WAVE ${e.wave}`);else if(e.type==='rest')motion.banner('NICE! TAKE A BREATHER');}syncTarget();draw();maybeEnd();if(now-lastSave>1000){save();lastSave=now;}}requestAnimationFrame(frame);}void init();requestAnimationFrame(frame);
