// Same local WASM Zipformer runtime as practice. Voice never writes keyboard DOM.
export class Voice {
  constructor(onText,onStatus){this.onText=onText;this.onStatus=onStatus;this.enabled=false;this.epoch=0;this.stream=null;this.loading=false;this.starting=false;this.last='';this.blocked=true;
    window.addEventListener('wasm-asr-status',e=>{const label=String(e.detail.status||'');if(/could not|failed|unavailable/i.test(label)){this.loading=false;this.enabled=false;void this.stop();}onStatus(label);});
    window.addEventListener('wasm-asr-ready',()=>{this.loading=false;onStatus('Model ready');if(this.enabled&&!this.blocked)void this.start();});
  }
  setContext(id){if(this.context===id)return;this.context=id;this.epoch++;this.last='';if(this.stream)window.wasmAsrRecognizer?.reset(this.stream);}
  async enable(on){this.enabled=on;if(!on){await this.stop();this.onStatus('');return;}if(!window.wasmAsrRecognizer){if(!this.loading){this.loading=true;const script=document.createElement('script');script.src='/game-voice-loader.js';script.onerror=()=>{this.loading=false;this.onStatus('Model unavailable — toggle Voice to retry');};document.body.append(script);}this.onStatus('Loading voice model…');return;}if(!this.blocked)await this.start();}
  suspend(){this.blocked=true;this.epoch++;this.last='';if(this.stream)window.wasmAsrRecognizer?.reset(this.stream);}
  resume(){this.blocked=false;if(this.enabled)void this.start();}
  async start(){if(this.stream||this.starting||!this.enabled||this.blocked||!window.wasmAsrRecognizer)return;this.starting=true;const epoch=this.epoch;try{
    const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});
    if(!this.enabled||this.blocked||this.epoch!==epoch){media.getTracks().forEach(t=>t.stop());return;}
    this.media=media;this.ctx=new AudioContext({sampleRate:16000});await this.ctx.resume();this.source=this.ctx.createMediaStreamSource(media);this.processor=this.ctx.createScriptProcessor(1024,1,1);this.mute=this.ctx.createGain();this.mute.gain.value=0;this.stream=window.wasmAsrRecognizer.createStream();this.source.connect(this.processor);this.processor.connect(this.mute);this.mute.connect(this.ctx.destination);
    this.processor.onaudioprocess=e=>{if(this.blocked||!this.enabled||!this.context||!this.stream)return;const id=this.context,version=this.epoch,recognizer=window.wasmAsrRecognizer;let input=e.inputBuffer.getChannelData(0);const ratio=this.ctx.sampleRate/16000;if(ratio!==1){const output=new Float32Array(Math.floor(input.length/ratio));for(let i=0;i<output.length;i++){const a=Math.floor(i*ratio),b=Math.min(input.length,Math.floor((i+1)*ratio));let s=0;for(let j=a;j<b;j++)s+=input[j];output[i]=s/Math.max(1,b-a);}input=output;}this.stream.acceptWaveform(16000,input);while(recognizer.isReady(this.stream))recognizer.decode(this.stream);const result=recognizer.getResult(this.stream);const text=String(result?.text??result??'').trim();const end=recognizer.isEndpoint(this.stream);if(id===this.context&&version===this.epoch){const previous=this.last.split(/\s+/).filter(Boolean),current=text.split(/\s+/).filter(Boolean);let n=0;while(n<previous.length&&n<current.length&&previous[n]===current[n])n++;if(current.length>n)this.onText(current.slice(n),id,version);if(id===this.context&&version===this.epoch)this.last=end?'':text;}if(end&&this.stream)recognizer.reset(this.stream);};this.onStatus('Listening…');
  }catch(e){this.enabled=false;this.onStatus(e.name==='NotAllowedError'?'Microphone permission needed':'Microphone unavailable');await this.stop();}finally{this.starting=false;}}
  async stop(){this.epoch++;this.last='';if(this.processor)this.processor.onaudioprocess=null;this.processor?.disconnect();this.source?.disconnect();this.mute?.disconnect();this.media?.getTracks().forEach(t=>t.stop());this.stream?.free();this.stream=null;this.media=null;this.processor=null;this.source=null;this.mute=null;const ctx=this.ctx;this.ctx=null;if(ctx&&ctx.state!=='closed')await ctx.close().catch(()=>{});}
}
