import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const script=await readFile(new URL('../app.js',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'https://192.168.0.68:8775/youtube',runScripts:'outside-only'});
const w=dom.window;
w.HTMLElement.prototype.scrollIntoView=()=>{};
w.fetch=async()=>({ok:true,json:async()=>({count:181,topic:'Greetings'})});
w.eval(script);
const $=s=>w.document.querySelector(s);
const paths=[...w.document.querySelectorAll('.paths>.path-group')];
assert.ok(paths[0].querySelector('#conversationPath'));
assert.ok(paths[1].querySelector('#youtubePath'));
assert.ok(paths[2].querySelector('#bookList'));
assert.equal($('#practiceFrame').getAttribute('src'),'/youtube?embed=1');
assert.ok($('#practiceFrame').getAttribute('allow').includes("microphone 'self'"));
assert.equal($('#practiceCourseTopic').textContent,'YouTube');
assert.equal(w.location.search,'?mode=youtube');
assert.equal($('#youtubePath').getAttribute('aria-pressed'),'true');
$('[data-chapter="11"]').click();await new Promise(r=>setTimeout(r,5));
assert.ok($('#practiceFrame').src.includes('chapter=11'));
assert.equal(w.document.body.dataset.practiceMode,'book');
assert.equal(w.location.pathname,'/');assert.equal(w.location.search,'');
$('#youtubePath').click();assert.equal($('#practiceFrame').getAttribute('src'),'/youtube?embed=1');
$('#conversationPath').click();await new Promise(r=>setTimeout(r,5));
assert.equal(w.document.body.dataset.practiceMode,'conversation');
assert.ok($('#practiceFrame').src.includes('/practice/?course='));
dom.window.close();
const fragment=await readFile(new URL('../youtube-ui/youtube.html',import.meta.url),'utf8');
assert.ok(!fragment.includes('id="answerForm"'),'YouTube fragment never duplicates the exercise');
assert.ok(!fragment.includes('id="wordGrid"'));
const template=await readFile(new URL('../practice-ui/index.html',import.meta.url),'utf8');
const yt=new JSDOM(template.replace('<main class="page" id="practice">',fragment+'<main class="page" id="practice">'));
const d=yt.window.document;
const before=(a,b)=>Boolean(d.querySelector(a).compareDocumentPosition(d.querySelector(b))&yt.window.Node.DOCUMENT_POSITION_FOLLOWING);
assert.ok(before('#importForm','.video-frame'));
assert.ok(before('.video-frame','.practice-card'));
assert.ok(before('#answerEntry','#speedControl'));
assert.ok(d.querySelector('#previousSentence'));
assert.ok(d.querySelector('#nextSentence'));
assert.ok(d.querySelector('#levelInput'));
assert.equal(d.querySelectorAll('#answerForm').length,1);
assert.equal(d.querySelectorAll('#voiceToggle').length,1);
assert.equal(d.querySelector('.practice-footer'),null);
assert.equal(d.querySelector('#timelineDetails'),null);assert.equal(d.querySelector('#rangeForm'),null);
assert.equal(d.querySelector('#importTitle').className,'sr-only');
assert.equal(d.querySelectorAll('#speedControl button').length,5);
yt.window.close();
console.log('Integrated shell unit checks passed: Conversation → YouTube → Book, direct entry, mode switching, address → video → practice, no timeline, speed row below input.');
