import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const template=await readFile(new URL('../practice-ui/index.html',import.meta.url),'utf8');
const fragment=await readFile(new URL('../youtube-ui/youtube.html',import.meta.url),'utf8');
const appSource=await readFile(new URL('../practice-ui/app.js',import.meta.url),'utf8');
const youtubeCSS=await readFile(new URL('../youtube-ui/youtube.css',import.meta.url),'utf8');
const html=template.replace('<main class="page" id="practice">',fragment+'<main class="page" id="practice">').replace('<div class="listen-stage">','<div class="youtube-navigation"><span id="clipTime"></span></div><div class="listen-stage">');
const url='https://192.168.0.68:8771/youtube?embed=1&surface=extension&video=jNQXAC9IVRw&bridge=abcdefghijklmnopabcdefghijklmnop';
const dom=new JSDOM(html,{url,referrer:'chrome-extension://abcdefghijklmnopabcdefghijklmnop/panel.html',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;Object.assign(globalThis,{window:w,document:d,location:w.location,localStorage:w.localStorage});
w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>({measureText:t=>({width:t.length*10})});
const messageListeners=[],add=w.addEventListener.bind(w);w.addEventListener=(type,listener,options)=>{if(type==='message')messageListeners.push(listener);return add(type,listener,options);};
let fetches=0;globalThis.fetch=w.fetch=async()=>{fetches++;throw new Error('LR surface must not call DictAI APIs');};
const messages=[],fakeParent={postMessage:(message,origin)=>messages.push({message,origin})};Object.defineProperty(w,'parent',{value:fakeParent});
const append=d.body.append.bind(d.body);d.body.append=(...nodes)=>{append(...nodes);for(const node of nodes)if(node.tagName==='SCRIPT'&&node.src.includes('/practice/app.js')){w.eval(appSource);queueMicrotask(()=>node.onload());}};
await import('../youtube-ui/youtube.js?lr-surface-test');await new Promise(r=>setTimeout(r,20));
assert.ok(d.body.classList.contains('extension-surface'));assert.ok(messages.some(x=>x.message.type==='need-captions'));assert.equal(fetches,0);
assert.equal(d.getElementById('headerStep').parentElement.className,'practice-card');
assert.match(youtubeCSS,/extension-surface \.practice-card\{display:block;min-height:0/);
assert.match(youtubeCSS,/practice-card>\.step-label\{display:flex!important;margin:18px 0 0 auto!important/);
const payload={videoId:'jNQXAC9IVRw',title:'Fixture',language:'en',cues:[{start:1,duration:2,text:'Hello world.'},{start:4,duration:2,text:'Next line.'}]};
for(const listener of messageListeners)listener({source:fakeParent,origin:'chrome-extension://abcdefghijklmnopabcdefghijklmnop',data:{channel:'dictai-panel-event-v2',type:'captions',payload}});
await new Promise(r=>setTimeout(r,30));
assert.equal(d.getElementById('wordGrid').children.length,2);assert.equal(d.getElementById('answerInput').disabled,false);assert.equal(fetches,0);
d.querySelector('[data-speed-level="3"]').click();await new Promise(r=>setTimeout(r,5));
assert.ok(messages.some(x=>x.message.type==='media'&&x.message.action==='play'&&x.message.start===.88));
assert.equal(d.getElementById('voiceToggle').checked,false);assert.equal(d.getElementById('redoButton').hidden,true);
w.close();console.log('LR surface checks passed: automatic request, browser caption delivery, shared practice UI, local operations and parent YouTube playback.');
